In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({"studentid":list(range(1001,1010)),"age":[24,26,np.nan,"Ankita",15,18,"20",20.6,"19.4"]})
df

   studentid     age
0       1001      24
1       1002      26
2       1003     NaN
3       1004  Ankita
4       1005      15
5       1006      18
6       1007      20
7       1008    20.6
8       1009    19.4

In [3]:
df["age"].unique().tolist()

[24, 26, nan, 'Ankita', 15, 18, '20', 20.6, '19.4']

In [4]:
df.columns.tolist()

['studentid', 'age']

In [8]:
#Observe the wrong data
l=[]
for i in  df["age"].unique().tolist():
    if type(i) not in [int,float]:
        l.append(i)
    
print(l)

['Ankita', '20', '19.4']

In [9]:
# filter /select the wrong data
df[df["age"].isin(l)]

   studentid     age
3       1004  Ankita
6       1007      20
8       1009    19.4

##### treat the wrong data

df.drop(index=df[df["age"].isin(l)].index.tolist())

##### replace

##### 1. replace with original value by contacting backend team (best option)

In [15]:
# df.iloc[index] =new values
df.iloc[[3,6,8],1]=[25,26,27]

##### 2. replace with statistical value (mean for numeric, mode for categorical)

In [18]:
df.iloc[[3,6,8],1]=df["age"].mean()

In [19]:
df

   studentid   age
0       1001    24
1       1002    26
2       1003   NaN
3       1004  22.7
4       1005    15
5       1006    18
6       1007  22.7
7       1008  20.6
8       1009  22.7

#### Duplicates

In [21]:
df = pd.DataFrame({"studentid":[101,102,102,103,104],"age":[24,27,27,28,29]})
df

   studentid  age
0        101   24
1        102   27
2        102   27
3        103   28
4        104   29

In [22]:
# observe the duplicates
df.duplicated().sum()

np.int64(1)

In [23]:
# filter the duplicates
df[df.duplicated()]

   studentid  age
2        102   27

In [24]:
# treat the duplicates()
df = df.drop_duplicates()

In [25]:
df

   studentid  age
0        101   24
1        102   27
3        103   28
4        104   29

In [26]:
df = pd.DataFrame({"studentid":[101,102,102,103,104],"age":[24,27,27,28,29]})
df

   studentid  age
0        101   24
1        102   27
2        102   27
3        103   28
4        104   29

In [27]:
df["studentid"].duplicated().sum()

np.int64(1)

In [28]:
df[df["studentid"].duplicated()]

   studentid  age
2        102   27

In [29]:
df[df["studentid"]==102]

   studentid  age
1        102   27
2        102   27

In [30]:
df.drop(index=1)

   studentid  age
0        101   24
2        102   27
3        103   28
4        104   29

#### Missing Values

In [31]:
df = pd.DataFrame({"studentid":[101,102,np.nan,104,105],"age":[24,27,np.nan,28,np.nan]})
df

   studentid   age
0      101.0  24.0
1      102.0  27.0
2        NaN   NaN
3      104.0  28.0
4      105.0   NaN

In [32]:
# observe the missing values
df.isnull()

   studentid    age
0      False  False
1      False  False
2       True   True
3      False  False
4      False   True

In [33]:
# to observe no.of missing values in each column
df.isnull().sum()

studentid    1
age          2
dtype: int64

In [37]:
# to observe % of missinf values in each column
df.isnull().sum()/df.shape[0]*100

studentid    20.0
age          40.0
dtype: float64

In [39]:
# to observe no.of missing values in each row
df.isnull().sum(axis=1)

0    0
1    0
2    2
3    0
4    1
dtype: int64

In [40]:
# to observe % of missing values in each row
df.isnull().sum(axis=1)/df.shape[1]*100

0      0.0
1      0.0
2    100.0
3      0.0
4     50.0
dtype: float64

In [41]:
# filter/extract the missing values
df[df["age"].isnull()]

   studentid  age
2        NaN  NaN
4      105.0  NaN

#### treat missing values

#### 1.Drop/Remove the missing values

In [44]:
df.drop(index=df[df["age"].isnull()].index)

   studentid   age
0      101.0  24.0
1      102.0  27.0
3      104.0  28.0

In [45]:
df.dropna()

   studentid   age
0      101.0  24.0
1      102.0  27.0
3      104.0  28.0

In [47]:
df["age"] = df["age"].fillna(20)

In [48]:
df

   studentid   age
0      101.0  24.0
1      102.0  27.0
2        NaN  20.0
3      104.0  28.0
4      105.0  20.0

#### Unimportant columns

In [50]:
 # df = df.drop(columns=[ , , ,])

##### Outliers

##### how to observe the outliers

In [53]:
df = pd.DataFrame({"X":[1,26,5,10,15,20,18,14,19,24,30,36,22,27,100,150]})
df

      X
0     1
1    26
2     5
3    10
4    15
5    20
6    18
7    14
8    19
9    24
10   30
11   36
12   22
13   27
14  100
15  150

In [54]:
Q1 = df["X"].quantile(0.25)
Q3 =df["X"].quantile(0.75)

IQR=Q3-Q1

ll=Q1-(1.5*IQR)
print("lower limit:",ll)
ul=Q3+(1.5*IQR)
print("upper Limit:",ul)

lower limit: -4.75
upper Limit: 47.25

In [56]:
df["X"].quantile([0,0.25,0.5,0.75,1])

0.00      1.00
0.25     14.75
0.50     21.00
0.75     27.75
1.00    150.00
Name: X, dtype: float64

##### extract iutliers

In [59]:
df[(df["X"]<ll) | (df["X"]>ul)]

      X
14  100
15  150

In [60]:
df[(df["X"]<ll) | (df["X"]>ul)].shape[0]

2